root: true
reportUnusedDisableDirectives: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  sourceType: module
env:
  es2021: true
plugins:
  - simple-import-sort
rules:
  dot-notation: warn
  eqeqeq:
    - warn
    - smart
  func-names:
    - warn
    - as-needed
  func-style:
    - warn
    - declaration
    - allowArrowFunctions: true
  no-alert: warn
  no-console: warn
  no-implicit-coercion: warn
  no-throw-literal: warn
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
overrides:
  - files: '*'
    env:
      node: true
  - files:
      - src*/**/*.ts
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier
    parserOptions:
      project: ./tsconfig.json
    rules:
      '@typescript-eslint/no-unused-vars': off
  - files:
      - src/**/*.spec.*
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
    rules:
      jest/expect-expect:
        - warn
        - assertFunctionNames:
            - expect
            - expectTypeOf
      jest/no-test-return-statement: warn
      jest/prefer-called-with: warn
      jest/prefer-spy-on: warn
      jest/prefer-strict-equal: warn
      jest/prefer-todo: warn
