root: true
reportUnusedDisableDirectives: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - simple-import-sort
rules:
  array-callback-return: error
  block-scoped-var: error
  camelcase: off
  consistent-this: error
  curly:
    - error
    - all
  dot-notation: error
  eqeqeq:
    - error
    - allow-null
  func-names:
    - error
    - as-needed
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  guard-for-in: error
  handle-callback-err: error
  max-depth: error
  max-params:
    - error
    - 5
  max-statements-per-line: error
  new-cap: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-console: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-iterator: error
  no-label-var: error
  no-labels:
    - error
    - allowLoop: true
  no-lone-blocks: error
  no-loop-func: error
  no-mixed-requires:
    - error
    - grouping: true
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-symbol: error
  no-new-wrappers: error
  no-octal-escape: error
  no-path-concat: error
  no-param-reassign: error
  no-proto: error
  no-prototype-builtins: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow-restricted-names: error
  no-throw-literal: error
  no-undef-init: error
  no-unneeded-ternary: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  no-void: error
  no-with: error
  object-shorthand: error
  operator-assignment: error
  padding-line-between-statements: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  radix: error
  spaced-comment:
    - error
    - always
    - block:
        balanced: true
  strict:
    - error
    - never
  vars-on-top: error
  yoda: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
overrides:
  - files: '*'
    env:
      node: true
  - files:
      - examples/**/*
      - packages/**/*
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
    parserOptions:
      project: ./tsconfig.json
    env:
      browser: true
      es6: true
    plugins:
      - '@typescript-eslint'
    rules:
      '@typescript-eslint/array-type':
        - error
        - default: array-simple
      '@typescript-eslint/await-thenable': error
      '@typescript-eslint/ban-types': off
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/explicit-member-accessibility':
        - error
        - accessibility: no-public
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/interface-name-prefix': off
      '@typescript-eslint/no-empty-function': error
      '@typescript-eslint/no-empty-interface': off
      '@typescript-eslint/no-explicit-any':
        - error
        - fixToUnknown: true
      '@typescript-eslint/no-extraneous-class': error
      '@typescript-eslint/no-for-in-array': error
      '@typescript-eslint/no-inferrable-types':
        - error
        - ignoreParameters: false
          ignoreProperties: false
      '@typescript-eslint/no-misused-new': error
      '@typescript-eslint/no-non-null-assertion': error
      '@typescript-eslint/no-parameter-properties': error
      '@typescript-eslint/no-require-imports': error
      '@typescript-eslint/no-shadow': error
      '@typescript-eslint/no-this-alias': error
      '@typescript-eslint/no-unnecessary-qualifier': error
      '@typescript-eslint/no-unnecessary-type-assertion': error
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: ^_
          caughtErrors: all
          ignoreRestSiblings: true
          varsIgnorePattern: ^_
      '@typescript-eslint/no-use-before-define':
        - error
        - nofunc
      '@typescript-eslint/no-useless-constructor': error
      '@typescript-eslint/prefer-for-of': error
      '@typescript-eslint/prefer-function-type': error
      '@typescript-eslint/prefer-includes': error
      '@typescript-eslint/prefer-readonly': error
      '@typescript-eslint/prefer-regexp-exec': error
      '@typescript-eslint/prefer-string-starts-ends-with': error
      '@typescript-eslint/require-await': error
      '@typescript-eslint/restrict-plus-operands': error
      '@typescript-eslint/unified-signatures': error
  - files:
      - examples/**/*.tsx
      - packages/**/*.tsx
    extends:
      - plugin:react/recommended
      - prettier/react
    settings:
      react:
        version: 'detect'
    plugins:
      - react-hooks
    rules:
      react/boolean-prop-naming: error
      react/default-props-match-prop-types:
        - error
        - allowRequiredDefaults: true
      react/display-name: off
      react/forbid-dom-props: error
      react/forbid-foreign-prop-types: error
      react/jsx-boolean-value: error
      react/jsx-curly-brace-presence: error
      react/jsx-filename-extension:
        - error
        - extensions:
            - .tsx
      react/jsx-fragments: error
      react/jsx-key:
        - error
        - checkFragmentShorthand: true
      react/jsx-no-script-url: error
      react/jsx-sort-default-props: error
      react/no-danger: error
      react/no-redundant-should-component-update: error
      react/no-typos: error
      react/no-unused-prop-types: error
      react/no-unused-state: error
      react/no-will-update-set-state: error
      react/prefer-es6-class: error
      react/prefer-read-only-props: error
      react/prop-types: off
      react/sort-comp: error
      react/static-property-placement: error
      react/style-prop-object: error
      react/void-dom-elements-no-children: error
      react-hooks/rules-of-hooks: error
      react-hooks/exhaustive-deps: error
  - files:
      - packages/**/*.spec.*
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
    rules:
      jest/no-test-return-statement: error
      jest/prefer-called-with: error
      jest/prefer-spy-on: error
      jest/prefer-strict-equal: error
      jest/prefer-todo: error
