version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '15'
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run:
                name: Install dependencies
                command: yarn install --frozen-lockfile
      - run:
          name: Check code formatting
          command: yarn run lint:check-prettier-conflicts && yarn run prettier:check
          when: always
      - run:
          name: Lint
          command: yarn run lint
          when: always
      - run:
          name: Run unit tests
          command: yarn test --ci --runInBand
          when: always
      - run:
          name: Build
          command: yarn run build
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - dist
  release:
    executor:
      name: node/default
      tag: '15'
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps: []
      - attach_workspace:
          at: dist
      - run: ls dist
      - run:
          name: Release
          command: yarn run release
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
