version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Check code formatting
          command: yarn run lint:check-prettier-conflicts && yarn run prettier:check
          when: always
      - run:
          name: Lint
          command: yarn run lint
          when: always
      - run:
          name: Run unit tests
          command: yarn test --coverageReporters lcov --ci --runInBand
          when: always
      - run:
          name: Report coverage to codecov
          command: yarn run test:report-coverage
          when: always
      - run:
          name: Build
          command: yarn run build
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - dist
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: yarn run release
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
